# Site settings
title: ColorSnapper 2
email: support@koolesache.com
description: > # this means to ignore newlines until "baseurl:"
  ColorSnapper2 is the easiest way for designers & developers to collect, adjust, organize and export colors of any pixel of the screen.
baseurl: "" # the subpath of your site, e.g. /blog/
webpackurl: "//localhost:8081"
url: "http://colorsnapper.com" # the base hostname & protocol for your site
twitter_username: colorsnapper

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title.html
exclude: ["node_modules", "gulpfile.js", "package.json", "webpack.config.js", "Gemfile", "Gemfile.lock", "README"]
production: false
