# Site settings
title: ColorSnapper2
description: >
  The Mac OS X color picker app for designers & developers which makes it easy to collect, adjust, organize and export colors of any pixel on the screen.
keywords: >
  color picker mac, color picker, colorpicker, color, picker, mac, color value,
  application, app, osx, apple, pick retina pixel mac, HiDPI pixel,
  adjust, export, favorite, favourite, manage, retina, HiDPI, precision,
  gesture, shortcut, css, cocoa, rgb, hsl, hex, swift, uicolor, .NET,
  colour, pixel, web, screen, photoshop, illustrator, bgcolor, fgcolor,
  background, foreground
email: support@koolesache.com
twitter_username: colorsnapper
mas_product_id: ""
paddle_product_id: 499167
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://colorsnapper.com" # the base hostname & protocol for your site
webpackurl: "//localhost:8081"

# Build settings
markdown: kramdown
permalink: /blog/:categories/:year/:month/:day/:title.html
exclude: ["node_modules", "gulpfile.js", "package.json", "webpack.config.js", "Gemfile", "Gemfile.lock", "README"]
production: false
